
    FROM node:20 AS builder

    RUN npm install -g n && n 23.8.0
    ENV PATH="/usr/local/n/versions/node/23.8.0/bin:$PATH"
    
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm ci
    
    COPY . .
    RUN rm -f .env
    
    ARG VITE_AUTHORITY_REALM
    ARG VITE_AUTHORITY_CLIENT_ID
    ARG VITE_AUTHORITY_REDIRECT_URI
    ARG VITE_AUTHORITY_SILENT_REDIRECT_URI
    ARG VITE_AUTHORITY_POST_LOGOUT_REDIRECT_URI
    ARG VITE_AUTHORITY_RESPONSE_TYPE
    ARG VITE_AUTHORITY_SCOPE
    ARG VITE_API_HOST

    
    ENV VITE_AUTHORITY_REALM=$VITE_AUTHORITY_REALM
    ENV VITE_AUTHORITY_CLIENT_ID=$VITE_AUTHORITY_CLIENT_ID
    ENV VITE_AUTHORITY_REDIRECT_URI=$VITE_AUTHORITY_REDIRECT_URI
    ENV VITE_AUTHORITY_SILENT_REDIRECT_URI=$VITE_AUTHORITY_SILENT_REDIRECT_URI
    ENV VITE_AUTHORITY_POST_LOGOUT_REDIRECT_URI=$VITE_AUTHORITY_POST_LOGOUT_REDIRECT_URI
    ENV VITE_AUTHORITY_RESPONSE_TYPE=$VITE_AUTHORITY_RESPONSE_TYPE
    ENV VITE_AUTHORITY_SCOPE=$VITE_AUTHORITY_SCOPE
    ENV VITE_API_HOST=$VITE_API_HOST
    

    RUN npm run build
    
    FROM nginx:alpine
    
    COPY --from=builder /app/dist /usr/share/nginx/html

    COPY nginx/default.conf /etc/nginx/conf.d/default.conf
    
    EXPOSE 80
    CMD ["nginx", "-g", "daemon off;"]
    