services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"

  api-server:
    build: ./apimock
    ports:
      - "4000:4000"
