services:
  ticketera-db:
    image: postgres:15
    container_name: ticketera-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ticketera_data:/var/lib/postgresql/data
  ticketera-api:
    image: ghcr.io/leandrodalbo/ticketera:latest
    container_name: ticketera-api
    ports:
      - 8082:8082
    depends_on:
      - ticketera-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ticketera-db:5432/ticketera
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=2000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=5
      - SPRING_FLYWAY_URL=jdbc:postgresql://ticketera-db:5432/ticketera
      - SPRING_FLYWAY_USER=user
      - SPRING_FLYWAY_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW_SQL=false
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_KEY=test
      - AWS_REGION=us-east-1
      - AWS_BUCKET=bucket-name

  # event-gateway:
  #   image: ghcr.io/leandrodalbo/event-gateway:latest
  #   container_name: event-gateway
  #   depends_on:
  #     - ticketera-api
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - KEYCLOAK_REALM_URI=http://keycloak:8080/realms/ticketera
  #     - EVENTS_API_URI=http://ticketera-api:8082

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"

volumes:
  ticketera_data:
